-- Free/Pro host controls
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "maxGuests" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "maxMedia" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "maxMediaPerGuest" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "uploadWindowHours" INTEGER;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "uploadsOpenAt" TIMESTAMP(3);
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "uploadsCloseAt" TIMESTAMP(3);
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "mapsUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "inviteCopy" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "inviteStickers" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "guestVisibility" TEXT NOT NULL DEFAULT 'own_only';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "requireApproval" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "publishMessage" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);

ALTER TABLE "Membership" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT;
ALTER TABLE "Membership" ADD COLUMN IF NOT EXISTS "contactWhatsapp" TEXT;
ALTER TABLE "Membership" ADD COLUMN IF NOT EXISTS "notificationsOptIn" BOOLEAN NOT NULL DEFAULT true;
